/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IIonEllipsisVertical: typeof import('~icons/ion/ellipsis-vertical')['default']
    IMaterialSymbolsBrightnessAlertOutlineRounded: typeof import('~icons/material-symbols/brightness-alert-outline-rounded')['default']
    IMdiBankTransfer: typeof import('~icons/mdi/bank-transfer')['default']
    IMdiBankTransferIn: typeof import('~icons/mdi/bank-transfer-in')['default']
    IMdiBankTransferOut: typeof import('~icons/mdi/bank-transfer-out')['default']
    IMdiCallSplit: typeof import('~icons/mdi/call-split')['default']
    IMdiCheck: typeof import('~icons/mdi/check')['default']
    IMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiEdit: typeof import('~icons/mdi/edit')['default']
    IMdiEllipsisVertical: typeof import('~icons/mdi/ellipsis-vertical')['default']
    IMdiExport: typeof import('~icons/mdi/export')['default']
    IMdiFile: typeof import('~icons/mdi/file')['default']
    IMdiFilter: typeof import('~icons/mdi/filter')['default']
    IMdiHistory: typeof import('~icons/mdi/history')['default']
    IMdiLink: typeof import('~icons/mdi/link')['default']
    IMdiLock: typeof import('~icons/mdi/lock')['default']
    IMdiMinus: typeof import('~icons/mdi/minus')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiSearch: typeof import('~icons/mdi/search')['default']
    IMdiSort: typeof import('~icons/mdi/sort')['default']
    IMdiStar: typeof import('~icons/mdi/star')['default']
    IMdiStarOutline: typeof import('~icons/mdi/star-outline')['default']
    IMdiSync: typeof import('~icons/mdi/sync')['default']
    IMdiTrash: typeof import('~icons/mdi/trash')['default']
  }
}
