/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IIcRoundQueryStats: typeof import('~icons/ic/round-query-stats')['default']
    IIonEllipsisVertical: typeof import('~icons/ion/ellipsis-vertical')['default']
    IMaterialSymbolsBrightnessAlertOutlineRounded: typeof import('~icons/material-symbols/brightness-alert-outline-rounded')['default']
    IMaterialSymbolsHomeWorkOutline: typeof import('~icons/material-symbols/home-work-outline')['default']
    IMdiBankTransfer: typeof import('~icons/mdi/bank-transfer')['default']
    IMdiBankTransferIn: typeof import('~icons/mdi/bank-transfer-in')['default']
    IMdiBankTransferOut: typeof import('~icons/mdi/bank-transfer-out')['default']
    IMdiBell: typeof import('~icons/mdi/bell')['default']
    IMdiCallSplit: typeof import('~icons/mdi/call-split')['default']
    IMdiCheck: typeof import('~icons/mdi/check')['default']
    IMdiCheckCircle: typeof import('~icons/mdi/check-circle')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiContentCopy: typeof import('~icons/mdi/content-copy')['default']
    IMdiCreditCard: typeof import('~icons/mdi/credit-card')['default']
    IMdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    IMdiDownload: typeof import('~icons/mdi/download')['default']
    IMdiEdit: typeof import('~icons/mdi/edit')['default']
    IMdiEllipsisVertical: typeof import('~icons/mdi/ellipsis-vertical')['default']
    IMdiExport: typeof import('~icons/mdi/export')['default']
    IMdiFile: typeof import('~icons/mdi/file')['default']
    IMdiFilePdfBox: typeof import('~icons/mdi/file-pdf-box')['default']
    IMdiFilter: typeof import('~icons/mdi/filter')['default']
    IMdiFolder: typeof import('~icons/mdi/folder')['default']
    IMdiHistory: typeof import('~icons/mdi/history')['default']
    IMdiLink: typeof import('~icons/mdi/link')['default']
    IMdiLock: typeof import('~icons/mdi/lock')['default']
    IMdiMinus: typeof import('~icons/mdi/minus')['default']
    IMdiMoney: typeof import('~icons/mdi/money')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiSearch: typeof import('~icons/mdi/search')['default']
    IMdiSort: typeof import('~icons/mdi/sort')['default']
    IMdiStar: typeof import('~icons/mdi/star')['default']
    IMdiSwapHorizontal: typeof import('~icons/mdi/swap-horizontal')['default']
    IMdiSync: typeof import('~icons/mdi/sync')['default']
    IMdiTimerStarOutline: typeof import('~icons/mdi/timer-star-outline')['default']
    IMdiTrash: typeof import('~icons/mdi/trash')['default']
    IMdiTrendingDown: typeof import('~icons/mdi/trending-down')['default']
    IMdiTrendingUp: typeof import('~icons/mdi/trending-up')['default']
  }
}
