/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IFluentFoodApple20Filled: typeof import('~icons/fluent/food-apple20-filled')['default']
    IMdiBankTransfer: typeof import('~icons/mdi/bank-transfer')['default']
    IMdiBankTransferIn: typeof import('~icons/mdi/bank-transfer-in')['default']
    IMdiBankTransferOut: typeof import('~icons/mdi/bank-transfer-out')['default']
    IMdiCallSplit: typeof import('~icons/mdi/call-split')['default']
    IMdiMinus: typeof import('~icons/mdi/minus')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiStar: typeof import('~icons/mdi/star')['default']
    IMdiStarOutline: typeof import('~icons/mdi/star-outline')['default']
    IMdiTrash: typeof import('~icons/mdi/trash')['default']
  }
}
